import { createContext, useContext, useMemo, useState } from 'react'

const LanguageContext = createContext()

const translations = {
  en: {
    nav: {
      shop: 'Shop',
      home: 'Home',
      discover: 'Discover',
      following: 'Following',
      brands: 'Brands',
      signIn: 'Sign In / Register',
      language: 'Language',
    },
    landingNav: {
      home: 'Home',
      about: 'About',
      contact: 'Contact',
    },
    hero: {
      heading: 'Discover The Best African Talent',
      blurb: 'From their feed to your closet. Own the pieces your favorites are rocking. Shop the looks you love.',
      shopNow: 'Shop Now',
      downloadApp: 'Download App',
      featuredBrands: 'Featured Brands',
      viewAllBrands: 'View all brands',
      exploreBrand: 'Explore brand',
      joinWaitlist: 'Join the Waitlist',
    },
    about: {
      heading: 'About Us',
      body1: 'Àgbáyémáarà is a fashion e-commerce platform that celebrates African talent and culture. We are dedicated to showcasing the best of African fashion, connecting customers with unique and stylish pieces from across the continent. Our mission is to empower African designers and artisans while providing our customers with an exceptional shopping experience.',
      body2: 'At Àgbáyémáarà, we believe in the power of fashion to tell stories and express individuality. We curate a diverse collection of clothing, accessories, and footwear that reflects the rich tapestry of African culture and creativity. Whether you are looking for traditional prints, contemporary designs, or statement pieces, you will find it all here.',
    },
    contact: {
      heading: 'Contact Us',
      intro: 'For inquiries, support, or feedback, please reach out to us at:',
      email: 'Email:',
      phone: 'Phone:',
      address: 'Address:',
      namePlaceholder: 'Your Name',
      emailPlaceholder: 'Your Email',
      messagePlaceholder: 'Your Message',
      send: 'Send Message',
    },
    footer: {
      rights: '© 2026 Àgbáyémáarà. All rights reserved.',
      privacy: 'Privacy Policy',
      terms: 'Terms of Service',
      follow: 'Follow us on social media',
      join: 'Join our community',
    },
    shopHome: {
      title: 'All Products',
      newIn: 'New In',
      onSale: 'On Sale',
      searchPlaceholder: 'Search products...',
      searchAriaLabel: 'Search products',
      noProductsMessage: 'No products match the current filters yet.',
      categories: {
        all: 'All',
        clothes: 'Clothes',
        shoes: 'Shoes',
        bags: 'Bags',
        jewelries: 'Jewelries',
        hats: 'Hats',
      },
      genderFilters: {
        all: 'All',
        female: 'Female',
        male: 'Male',
      },
    },
    productCard: {
      addToCart: 'Add to Cart',
      added: 'Added',
    },
    productDetails: {
      back: 'Back to products',
      addToCart: 'Add to Cart',
      continueShopping: 'Continue Shopping',
      overview: 'Overview',
      fastDelivery: 'Fast delivery',
      fastDeliveryText: 'Estimated delivery shown at checkout.',
      qualityGuarantee: 'Quality guarantee',
      qualityGuaranteeText: 'Carefully selected fabric and finish.',
      care: 'Care instructions',
      notFound: 'Product not found',
      return: 'Return to shop',
      inStock: 'In stock',
      madeToOrder: 'Made to order',
      soldOut: 'Sold out',
    },
    brandsPage: {
      badge: 'Brand Directory',
      heading: 'Discover brands that define the collection.',
      blurb: 'Explore a curated grid of labels. Tap any brand to open a dedicated collection page with all of its products.',
      brands: 'Brands',
      styleRange: 'Style range',
      layout: 'Layout',
      featured: 'Featured labels',
      shopByBrand: 'Shop by brand',
      gridView: 'Grid View',
      onSaleBadge: 'Sale',
      saleBrands: 'Brands on Sale',
      collection: 'Collection',
      viewBrand: 'View brand',
      curated: 'Curated',
      grid: 'Grid',
    },
    brandDetails: {
      notFound: 'Brand not found',
      backToBrands: 'Back to brands',
      featuredBrand: 'Featured brand',
      products: 'products',
      curatedCollection: 'Curated collection',
      quickOverview: 'Quick overview',
      selectedProducts: 'Selected products',
      selectedProductsText: 'items currently available in this collection.',
      browseByBrand: 'Browse by brand',
      browseByBrandText: 'Every card below opens the product detail page for that item.',
      productsFound: 'products found',
      noProducts: 'No products are currently listed for this brand.',
      productsLabel: 'Products',
      collectionLabel: 'collection',
      onSaleHeading: 'On Sale — 25% Off',
      onSaleProducts: 'on sale',
      featuredProduct: 'Featured product',
    },
    brandStory: {
      storyEyebrow: 'Brand Story',
      notFound: 'Story not found',
      backToBrand: 'Back to brand',
      featuredInStory: 'Featured in this story',
      shopThisPiece: 'Shop this piece',
      moreStories: 'More stories from',
      readStory: 'Read the story',
      tabHeading: 'Stories',
    },
    discountPopup: {
      heading: 'Flash Sale!',
      subheading: 'Get 25% off selected items — today only',
      limitedOffer: 'Limited time offer',
      cta: 'Start Shopping',
    },
    cart: {
      title: 'Your Cart',
      empty: 'Your cart is empty',
      continueShopping: 'Continue shopping',
      subtotal: 'Subtotal',
      shipping: 'Shipping and taxes calculated at checkout',
      checkout: 'Checkout',
      clearCart: 'Clear cart',
      brandFallback: 'Agbayemaara',
    },
    checkout: {
      back: 'Back',
      summaryTitle: 'Order Summary',
      shippingLabel: 'Shipping',
      shippingFree: 'Free',
      totalLabel: 'Total',
      deliveryTitle: 'Delivery Address',
      deliveryHint: 'Where should we send your pieces?',
      fullNameLabel: 'Full name',
      emailLabel: 'Email',
      phoneLabel: 'Phone',
      addressLabel: 'Address',
      cityLabel: 'City',
      countryLabel: 'Country',
      paymentTitle: 'Payment Method',
      paymentHint: 'All transactions are secure and encrypted.',
      cardLabel: 'Card',
      cardHint: 'Pay with card — powered by Paystack',
      transferLabel: 'Bank transfer',
      transferHint: 'Pay from your bank account',
      ussdLabel: 'USSD',
      ussdHint: 'Pay with a quick USSD code',
      mockNote: 'Demo checkout — no real payment is processed.',
      payButton: 'Pay',
      processingLabel: 'Processing payment…',
      successTitle: 'Order confirmed!',
      successBody: 'Thank you — your pieces are being prepared. A confirmation has been sent to your email.',
      referenceLabel: 'Order reference',
      paidLabel: 'Amount paid',
      deliveryEstimate: '3–7 business days',
      emptyCartTitle: 'Your cart is empty',
      emptyCartCta: 'Continue shopping',
      successShopCta: 'Continue shopping',
      successFeedCta: 'Back to feed',
    },
    orders: {
      navLink: 'My Orders',
      navAriaLabel: 'My orders',
      backToShop: 'Back to shop',
      title: 'My Orders',
      subtitle: 'Your mock purchases from this demo — stored on this device.',
      emptyTitle: 'No orders yet',
      emptyBody: 'When you place an order it will show up here with its reference, items, and delivery details.',
      emptyCta: 'Start shopping',
      viewItems: 'View items',
      hideItems: 'Hide items',
      viewOrdersCta: 'View my orders',
      status_created: 'Placed',
      status_paid: 'Paid',
      status_brand_notified: 'Brand notified',
      status_confirmed_by_brand: 'Brand confirmed',
      status_in_progress: 'In progress',
      status_processing: 'Processing',
      status_shipped: 'Shipped',
      status_delivered: 'Delivered',
      status_fulfilment_failed: 'Failed',
      status_refunded: 'Refunded',
    },
    orderStatus: {
      title: 'Order confirmed!',
      subtitle: 'Thank you — your pieces are being prepared. A confirmation has been sent to your email.',
      trackOrderCta: 'Track order',
      notFoundTitle: 'Order not found',
      notFoundBody: 'We could not find that order on this device. It may have been placed on another browser or cleared from storage.',
      stepOrdered: 'Ordered',
      stepInProgress: 'In Progress',
      stepShipped: 'Shipped',
      stepDelivered: 'Delivered',
      failedTitle: 'Fulfilment failed',
      failedSubtitle: 'The brand could not complete this order — no need to do anything. A refund is on its way to your original payment method.',
      stage_fulfilment_failed: 'Fulfilment failed — this order could not be completed. A refund has been initiated.',
      stage_refunded: 'Refunded — the full amount has been returned to your original payment method.',
      demoAdvance: 'Demo: advance status',
      demoFail: 'Demo: fail fulfilment',
      demoRefund: 'Demo: issue refund',
      demoReset: 'Demo: reset order',
    },
    auth: {
      brand: 'Agbayemaara',
      welcomeBack: 'Welcome back',
      createAccount: 'Create account',
      signInSubtitle: 'Sign in to access your orders and wishlist.',
      signUpSubtitle: 'Join and discover the best of African fashion.',
      signIn: 'Sign In',
      signUp: 'Sign Up',
      fullName: 'Full Name',
      fullNamePlaceholder: 'Your full name',
      email: 'Email',
      emailPlaceholder: 'you@example.com',
      password: 'Password',
      passwordPlaceholderSignin: '••••••••',
      passwordPlaceholderSignup: 'Min. 8 characters',
      forgotPassword: 'Forgot password?',
      signInButton: 'Sign In',
      createAccountButton: 'Create Account',
      continueWithGoogle: 'Continue with Google',
      openCart: 'Open cart',
      signInAction: 'Sign in',
      toggleMenu: 'Toggle menu',
    },
    discovery: {
      eyebrow: 'The Feed',
      title: 'Discover African fashion, story first',
      subtitle: 'Editorial, drops, milestones, and the labels behind them — one feed, newest first.',
      forYou: 'FOR YOU',
      followingTab: 'FOLLOWING',
      newBrands: 'NEW BRANDS',
      storyBadge: 'Story',
      stylingBadge: 'Styling',
      dropBadge: 'Drop',
      milestoneBadge: 'Milestone',
      newBrandBadge: 'New brand',
      saleBadge: 'Sale',
      shopTheLook: 'Shop the look',
      readStory: 'Read the story',
      follow: 'Follow',
      following: 'Following',
      viewBrand: 'View brand',
      productsLabel: 'products',
      firstDropTeaser: 'First drop just landed',
      emptyFeed: 'Nothing here yet — check back soon.',
      emptyFollowingTitle: 'Your feed is waiting',
      emptyFollowingBody: 'Follow the brands you love and their stories, drops, and milestones will land here first.',
      emptyFollowingCta: 'Explore For You',
      errorTitle: 'The feed hit a snag',
      errorBody: 'Something went wrong loading your feed. Give it another go.',
      retry: 'Try again',
    },
    followingPage: {
      navLink: 'Following',
      eyebrow: 'Your Follows',
      title: 'Following',
      subtitle: 'Stories, drops, milestones, and pieces from the brands you follow — one feed, newest first.',
      emptyTitle: 'Your feed is waiting',
      emptyBody: 'Follow the brands you love and their stories, drops, milestones, and products will land here first. Start with these three.',
      emptyCta: 'Explore Discovery',
      brandsFollowed: 'brands followed',
    },
  },
  es: {
    nav: {
      shop: 'Tienda',
      home: 'Inicio',
      discover: 'Descubrir',
      following: 'Siguiendo',
      brands: 'Marcas',
      signIn: 'Iniciar sesión / Registrarse',
      language: 'Idioma',
    },
    landingNav: {
      home: 'Inicio',
      about: 'Acerca de',
      contact: 'Contacto',
    },
    hero: {
      heading: 'Descubre el mejor talento africano',
      blurb: 'Desde su feed hasta tu armario. Haz tuyas las piezas que tus favoritos lucen. Compra los looks que te encantan.',
      shopNow: 'Comprar ahora',
      downloadApp: 'Descargar app',
      featuredBrands: 'Marcas destacadas',
      viewAllBrands: 'Ver todas las marcas',
      exploreBrand: 'Explorar marca',
      joinWaitlist: 'Únete a la lista de espera',
    },
    about: {
      heading: 'Sobre nosotros',
      body1: 'Agbayemaara es una plataforma de moda en línea que celebra el talento y la cultura africanos. Nos dedicamos a mostrar lo mejor de la moda africana, conectando a los clientes con piezas únicas y elegantes de todo el continente. Nuestra misión es empoderar a diseñadores y artesanos africanos mientras ofrecemos a nuestros clientes una experiencia de compra excepcional.',
      body2: 'En Agbayemaara, creemos en el poder de la moda para contar historias y expresar la individualidad. Curamos una colección diversa de ropa, accesorios y calzado que refleja el rico tapiz de la cultura y la creatividad africanas. Ya sea que busques estampados tradicionales, diseños contemporáneos o piezas llamativas, aquí encontrarás todo.',
    },
    contact: {
      heading: 'Contáctanos',
      intro: 'Para consultas, soporte o comentarios, ponte en contacto con nosotros en:',
      email: 'Correo:',
      phone: 'Teléfono:',
      address: 'Dirección:',
      namePlaceholder: 'Tu nombre',
      emailPlaceholder: 'Tu correo',
      messagePlaceholder: 'Tu mensaje',
      send: 'Enviar mensaje',
    },
    footer: {
      rights: '© 2026 Agbayemaara. Todos los derechos reservados.',
      privacy: 'Política de privacidad',
      terms: 'Términos de servicio',
      follow: 'Síguenos en redes sociales',
      join: 'Únete a nuestra comunidad',
    },
    shopHome: {
      title: 'Todos los productos',
      newIn: 'Novedades',
      onSale: 'En Oferta',
      searchPlaceholder: 'Buscar productos...',
      searchAriaLabel: 'Buscar productos',
      noProductsMessage: 'No hay productos que coincidan con los filtros actuales.',
      categories: {
        all: 'Todo',
        clothes: 'Ropa',
        shoes: 'Zapatos',
        bags: 'Bolsos',
        jewelries: 'Joyas',
        hats: 'Sombreros',
      },
      genderFilters: {
        all: 'Todo',
        female: 'Mujer',
        male: 'Hombre',
      },
    },
    productCard: {
      addToCart: 'Añadir al carrito',
      added: 'Añadido',
    },
    productDetails: {
      back: 'Volver a productos',
      addToCart: 'Añadir al carrito',
      continueShopping: 'Seguir comprando',
      overview: 'Resumen',
      fastDelivery: 'Entrega rápida',
      fastDeliveryText: 'La fecha estimada de entrega se muestra al finalizar la compra.',
      qualityGuarantee: 'Garantía de calidad',
      qualityGuaranteeText: 'Tela y acabado cuidadosamente seleccionados.',
      care: 'Instrucciones de cuidado',
      notFound: 'Producto no encontrado',
      return: 'Volver a la tienda',
      inStock: 'En existencia',
      madeToOrder: 'Por encargo',
      soldOut: 'Agotado',
    },
    brandsPage: {
      badge: 'Directorio de marcas',
      heading: 'Descubre las marcas que definen la colección.',
      blurb: 'Explora una cuadrícula curada de etiquetas. Toca cualquier marca para abrir una página dedicada con todos sus productos.',
      brands: 'Marcas',
      styleRange: 'Gama de estilo',
      layout: 'Diseño',
      featured: 'Etiquetas destacadas',
      shopByBrand: 'Comprar por marca',
      gridView: 'Vista en cuadrícula',
      onSaleBadge: 'Oferta',
      saleBrands: 'Marcas en Oferta',
      collection: 'Colección',
      viewBrand: 'Ver marca',
      curated: 'Curada',
      grid: 'Cuadrícula',
    },
    brandDetails: {
      notFound: 'Marca no encontrada',
      backToBrands: 'Volver a marcas',
      featuredBrand: 'Marca destacada',
      products: 'productos',
      curatedCollection: 'Colección curada',
      quickOverview: 'Resumen rápido',
      selectedProducts: 'Productos seleccionados',
      selectedProductsText: 'artículos disponibles actualmente en esta colección.',
      browseByBrand: 'Explorar por marca',
      browseByBrandText: 'Cada tarjeta a continuación abre la página de detalles del producto para ese artículo.',
      productsFound: 'productos encontrados',
      noProducts: 'Actualmente no hay productos listados para esta marca.',
      productsLabel: 'Productos',
      collectionLabel: 'colección',
      onSaleHeading: 'En Oferta — 25% Dto.',
      onSaleProducts: 'en oferta',
      featuredProduct: 'Producto destacado',
    },
    brandStory: {
      storyEyebrow: 'Historia de la marca',
      notFound: 'Historia no encontrada',
      backToBrand: 'Volver a la marca',
      featuredInStory: 'Destacado en esta historia',
      shopThisPiece: 'Comprar esta pieza',
      moreStories: 'Más historias de',
      readStory: 'Leer la historia',
      tabHeading: 'Historias',
    },
    discountPopup: {
      heading: '¡Venta Flash!',
      subheading: 'Obtén 25% de descuento en artículos seleccionados — solo hoy',
      limitedOffer: 'Oferta por tiempo limitado',
      cta: 'Empezar a comprar',
    },
    cart: {
      title: 'Tu carrito',
      empty: 'Tu carrito está vacío',
      continueShopping: 'Seguir comprando',
      subtotal: 'Subtotal',
      shipping: 'Envío e impuestos calculados al finalizar la compra',
      checkout: 'Pagar',
      clearCart: 'Vaciar carrito',
      brandFallback: 'Àgbáyémáarà',
    },
    checkout: {
      back: 'Volver',
      summaryTitle: 'Resumen del pedido',
      shippingLabel: 'Envío',
      shippingFree: 'Gratis',
      totalLabel: 'Total',
      deliveryTitle: 'Dirección de entrega',
      deliveryHint: '¿Dónde enviamos tus piezas?',
      fullNameLabel: 'Nombre completo',
      emailLabel: 'Correo',
      phoneLabel: 'Teléfono',
      addressLabel: 'Dirección',
      cityLabel: 'Ciudad',
      countryLabel: 'País',
      paymentTitle: 'Método de pago',
      paymentHint: 'Todas las transacciones son seguras y están cifradas.',
      cardLabel: 'Tarjeta',
      cardHint: 'Paga con tarjeta — con Paystack',
      transferLabel: 'Transferencia bancaria',
      transferHint: 'Paga desde tu cuenta bancaria',
      ussdLabel: 'USSD',
      ussdHint: 'Paga con un código USSD',
      mockNote: 'Demo de pago — no se procesa ningún pago real.',
      payButton: 'Pagar',
      processingLabel: 'Procesando pago…',
      successTitle: '¡Pedido confirmado!',
      successBody: 'Gracias — tus piezas se están preparando. Se ha enviado una confirmación a tu correo.',
      referenceLabel: 'Referencia del pedido',
      paidLabel: 'Monto pagado',
      deliveryEstimate: '3–7 días hábiles',
      emptyCartTitle: 'Tu carrito está vacío',
      emptyCartCta: 'Seguir comprando',
      successShopCta: 'Seguir comprando',
      successFeedCta: 'Volver al feed',
    },
    orders: {
      navLink: 'Mis pedidos',
      navAriaLabel: 'Mis pedidos',
      backToShop: 'Volver a la tienda',
      title: 'Mis pedidos',
      subtitle: 'Tus compras de demostración — almacenadas en este dispositivo.',
      emptyTitle: 'Aún no hay pedidos',
      emptyBody: 'Cuando hagas un pedido aparecerá aquí con su referencia, artículos y detalles de entrega.',
      emptyCta: 'Empezar a comprar',
      viewItems: 'Ver artículos',
      hideItems: 'Ocultar artículos',
      viewOrdersCta: 'Ver mis pedidos',
      status_created: 'Realizado',
      status_paid: 'Pagado',
      status_brand_notified: 'Marca notificada',
      status_confirmed_by_brand: 'Marca confirmada',
      status_in_progress: 'En progreso',
      status_processing: 'Procesando',
      status_shipped: 'Enviado',
      status_delivered: 'Entregado',
      status_fulfilment_failed: 'Fallido',
      status_refunded: 'Reembolsado',
    },
    orderStatus: {
      title: '¡Pedido confirmado!',
      subtitle: 'Gracias — tus piezas se están preparando. Se ha enviado una confirmación a tu correo.',
      trackOrderCta: 'Seguir pedido',
      notFoundTitle: 'Pedido no encontrado',
      notFoundBody: 'No pudimos encontrar ese pedido en este dispositivo. Puede que se haya realizado en otro navegador o que se haya eliminado del almacenamiento.',
      stepOrdered: 'Pedido',
      stepInProgress: 'En progreso',
      stepShipped: 'Enviado',
      stepDelivered: 'Entregado',
      failedTitle: 'El envío falló',
      failedSubtitle: 'La marca no pudo completar este pedido — no tienes que hacer nada. El reembolso va en camino a tu método de pago original.',
      stage_fulfilment_failed: 'El envío falló — este pedido no pudo completarse. Se ha iniciado un reembolso.',
      stage_refunded: 'Reembolsado — el monto total ha sido devuelto a tu método de pago original.',
      demoAdvance: 'Demo: avanzar estado',
      demoFail: 'Demo: simular fallo',
      demoRefund: 'Demo: emitir reembolso',
      demoReset: 'Demo: reiniciar pedido',
    },
    auth: {
      brand: 'Àgbáyémáarà',
      welcomeBack: 'Bienvenido de nuevo',
      createAccount: 'Crear cuenta',
      signInSubtitle: 'Inicia sesión para ver tus pedidos y tu lista de deseos.',
      signUpSubtitle: 'Únete y descubre lo mejor de la moda africana.',
      signIn: 'Iniciar sesión',
      signUp: 'Registrarse',
      fullName: 'Nombre completo',
      fullNamePlaceholder: 'Tu nombre completo',
      email: 'Correo',
      emailPlaceholder: 'tu@correo.com',
      password: 'Contraseña',
      passwordPlaceholderSignin: '••••••••',
      passwordPlaceholderSignup: 'Mín. 8 caracteres',
      forgotPassword: '¿Olvidaste tu contraseña?',
      signInButton: 'Iniciar sesión',
      createAccountButton: 'Crear cuenta',
      continueWithGoogle: 'Continuar con Google',
      openCart: 'Abrir carrito',
      signInAction: 'Iniciar sesión',
      toggleMenu: 'Alternar menú',
    },
    discovery: {
      eyebrow: 'El Feed',
      title: 'Descubre la moda africana, historia primero',
      subtitle: 'Editorial, lanzamientos, hitos y las marcas detrás de ellos — un solo feed, lo más nuevo primero.',
      forYou: 'PARA TI',
      followingTab: 'SIGUIENDO',
      newBrands: 'NUEVAS MARCAS',
      storyBadge: 'Historia',
      stylingBadge: 'Estilo',
      dropBadge: 'Lanzamiento',
      milestoneBadge: 'Hito',
      newBrandBadge: 'Nueva marca',
      saleBadge: 'Oferta',
      shopTheLook: 'Compra el look',
      readStory: 'Leer la historia',
      follow: 'Seguir',
      following: 'Siguiendo',
      viewBrand: 'Ver marca',
      productsLabel: 'productos',
      firstDropTeaser: 'Primer lanzamiento disponible',
      emptyFeed: 'Nada por aquí todavía — vuelve pronto.',
      emptyFollowingTitle: 'Tu feed te espera',
      emptyFollowingBody: 'Sigue a las marcas que te gustan y sus historias, lanzamientos e hitos llegarán aquí primero.',
      emptyFollowingCta: 'Explorar Para Ti',
      errorTitle: 'El feed tuvo un problema',
      errorBody: 'Algo salió mal al cargar tu feed. Inténtalo de nuevo.',
      retry: 'Reintentar',
    },
    followingPage: {
      navLink: 'Siguiendo',
      eyebrow: 'Tus seguimientos',
      title: 'Siguiendo',
      subtitle: 'Historias, lanzamientos, hitos y piezas de las marcas que sigues — un solo feed, lo más nuevo primero.',
      emptyTitle: 'Tu feed te espera',
      emptyBody: 'Sigue a las marcas que te gustan y sus historias, lanzamientos, hitos y productos llegarán aquí primero. Empieza con estas tres.',
      emptyCta: 'Explorar Descubrir',
      brandsFollowed: 'marcas seguidas',
    },
  },
  fr: {
    nav: {
      shop: 'Boutique',
      home: 'Accueil',
      discover: 'Découvrir',
      following: 'Abonnements',
      brands: 'Marques',
      signIn: 'Se connecter / S’inscrire',
      language: 'Langue',
    },
    landingNav: {
      home: 'Accueil',
      about: 'À propos',
      contact: 'Contact',
    },
    hero: {
      heading: 'Découvrez le meilleur talent africain',
      blurb: 'De leur fil à votre dressing. Prenez les pièces que vos favoris portent. Achetez les looks que vous aimez.',
      shopNow: 'Acheter maintenant',
      downloadApp: 'Télécharger l’application',
      featuredBrands: 'Marques en vedette',
      viewAllBrands: 'Voir toutes les marques',
      exploreBrand: 'Explorer la marque',
      joinWaitlist: 'Rejoindre la liste d\u2019attente',
    },
    about: {
      heading: 'À propos de nous',
      body1: 'Àgbáyémáarà est une plateforme e-commerce de mode qui célèbre le talent et la culture africains. Nous nous consacrons à mettre en valeur le meilleur de la mode africaine, en connectant les clients à des pièces uniques et élégantes de tout le continent. Notre mission est de donner de la voix aux créateurs et artisans africains tout en offrant à nos clients une expérience d’achat exceptionnelle.',
      body2: 'Chez Àgbáyémáarà, nous croyons au pouvoir de la mode pour raconter des histoires et exprimer l’individualité. Nous sélectionnons une collection variée de vêtements, accessoires et chaussures qui reflète la richesse de la culture et de la créativité africaines. Que vous recherchiez des imprimés traditionnels, des designs contemporains ou des pièces marquantes, vous trouverez tout ici.',
    },
    contact: {
      heading: 'Contactez-nous',
      intro: 'Pour toute demande, assistance ou retour, n’hésitez pas à nous contacter à :',
      email: 'Email :',
      phone: 'Téléphone :',
      address: 'Adresse :',
      namePlaceholder: 'Votre nom',
      emailPlaceholder: 'Votre email',
      messagePlaceholder: 'Votre message',
      send: 'Envoyer le message',
    },
    footer: {
      rights: '© 2026 Àgbáyémáarà. Tous droits réservés.',
      privacy: 'Politique de confidentialité',
      terms: 'Conditions d’utilisation',
      follow: 'Suivez-nous sur les réseaux sociaux',
      join: 'Rejoignez notre communauté',
    },
    shopHome: {
      title: 'Tous les produits',
      newIn: 'Nouveautés',
      onSale: 'En Solde',
      searchPlaceholder: 'Rechercher des produits...',
      searchAriaLabel: 'Rechercher des produits',
      noProductsMessage: 'Aucun produit ne correspond aux filtres actuels.',
      categories: {
        all: 'Tous',
        clothes: 'Vêtements',
        shoes: 'Chaussures',
        bags: 'Sacs',
        jewelries: 'Bijoux',
        hats: 'Chapeaux',
      },
      genderFilters: {
        all: 'Tous',
        female: 'Femme',
        male: 'Homme',
      },
    },
    productCard: {
      addToCart: 'Ajouter au panier',
      added: 'Ajouté',
    },
    productDetails: {
      back: 'Retour aux produits',
      addToCart: 'Ajouter au panier',
      continueShopping: 'Continuer les achats',
      overview: 'Aperçu',
      fastDelivery: 'Livraison rapide',
      fastDeliveryText: 'La livraison estimée est indiquée au moment du paiement.',
      qualityGuarantee: 'Garantie de qualité',
      qualityGuaranteeText: 'Tissu et finition soigneusement sélectionnés.',
      care: 'Instructions d’entretien',
      notFound: 'Produit introuvable',
      return: 'Retourner à la boutique',
      inStock: 'En stock',
      madeToOrder: 'Sur commande',
      soldOut: 'Épuisé',
    },
    brandsPage: {
      badge: 'Annuaire des marques',
      heading: 'Découvrez les marques qui définissent la collection.',
      blurb: 'Explorez une grille soignée de labels. Touchez une marque pour ouvrir une page dédiée avec tous ses produits.',
      brands: 'Marques',
      styleRange: 'Gammes de style',
      layout: 'Mise en page',
      featured: 'Labels en vedette',
      shopByBrand: 'Acheter par marque',
      gridView: 'Vue grille',
      onSaleBadge: 'Soldes',
      saleBrands: 'Marques en Solde',
      collection: 'Collection',
      viewBrand: 'Voir la marque',
      curated: 'Sélectionnée',
      grid: 'Grille',
    },
    brandDetails: {
      notFound: 'Marque introuvable',
      backToBrands: 'Retour aux marques',
      featuredBrand: 'Marque en vedette',
      products: 'produits',
      curatedCollection: 'Collection sélectionnée',
      quickOverview: 'Aperçu rapide',
      selectedProducts: 'Produits sélectionnés',
      selectedProductsText: 'articles actuellement disponibles dans cette collection.',
      browseByBrand: 'Parcourir par marque',
      browseByBrandText: 'Chaque carte ci-dessous ouvre la page de détail du produit correspondant.',
      productsFound: 'produits trouvés',
      noProducts: 'Aucun produit n’est actuellement listé pour cette marque.',
      productsLabel: 'Produits',
      collectionLabel: 'collection',
      onSaleHeading: 'En Solde — 25% de réduction',
      onSaleProducts: 'en solde',
      featuredProduct: 'Produit vedette',
    },
    brandStory: {
      storyEyebrow: 'Histoire de la marque',
      notFound: 'Histoire introuvable',
      backToBrand: 'Retour à la marque',
      featuredInStory: 'En vedette dans cette histoire',
      shopThisPiece: 'Acheter cette pièce',
      moreStories: 'Plus d’histoires de',
      readStory: 'Lire l’histoire',
      tabHeading: 'Histoires',
    },
    discountPopup: {
      heading: 'Vente Flash!',
      subheading: 'Obtenez 25% de réduction sur des articles sélectionnés — aujourd\u2019hui seulement',
      limitedOffer: 'Offre à durée limitée',
      cta: 'Commencer les achats',
    },
    cart: {
      title: 'Votre panier',
      empty: 'Votre panier est vide',
      continueShopping: 'Continuer les achats',
      subtotal: 'Sous-total',
      shipping: 'Frais de livraison et taxes calculés au paiement',
      checkout: 'Commander',
      clearCart: 'Vider le panier',
      brandFallback: 'Agbayemaara',
    },
    checkout: {
      back: 'Retour',
      summaryTitle: 'Résumé de la commande',
      shippingLabel: 'Livraison',
      shippingFree: 'Gratuite',
      totalLabel: 'Total',
      deliveryTitle: 'Adresse de livraison',
      deliveryHint: 'Où devons-nous envoyer vos pièces ?',
      fullNameLabel: 'Nom complet',
      emailLabel: 'Email',
      phoneLabel: 'Téléphone',
      addressLabel: 'Adresse',
      cityLabel: 'Ville',
      countryLabel: 'Pays',
      paymentTitle: 'Moyen de paiement',
      paymentHint: 'Toutes les transactions sont sécurisées et chiffrées.',
      cardLabel: 'Carte',
      cardHint: 'Payez par carte — via Paystack',
      transferLabel: 'Virement bancaire',
      transferHint: 'Payez depuis votre compte bancaire',
      ussdLabel: 'USSD',
      ussdHint: 'Payez avec un code USSD',
      mockNote: 'Démo de paiement — aucun paiement réel n’est traité.',
      payButton: 'Payer',
      processingLabel: 'Paiement en cours…',
      successTitle: 'Commande confirmée !',
      successBody: 'Merci — vos pièces sont en préparation. Une confirmation a été envoyée à votre email.',
      referenceLabel: 'Référence de commande',
      paidLabel: 'Montant payé',
      deliveryEstimate: '3–7 jours ouvrables',
      emptyCartTitle: 'Votre panier est vide',
      emptyCartCta: 'Continuer les achats',
      successShopCta: 'Continuer les achats',
      successFeedCta: 'Retour au fil',
    },
    orders: {
      navLink: 'Mes commandes',
      navAriaLabel: 'Mes commandes',
      backToShop: 'Retour à la boutique',
      title: 'Mes commandes',
      subtitle: 'Vos achats de démonstration — stockés sur cet appareil.',
      emptyTitle: 'Aucune commande pour le moment',
      emptyBody: 'Quand vous passez une commande, elle apparaîtra ici avec sa référence, ses articles et les détails de livraison.',
      emptyCta: 'Commencer les achats',
      viewItems: 'Voir les articles',
      hideItems: 'Masquer les articles',
      viewOrdersCta: 'Voir mes commandes',
      status_created: 'Passée',
      status_paid: 'Payée',
      status_brand_notified: 'Marque notifiée',
      status_confirmed_by_brand: 'Marque confirmée',
      status_in_progress: 'En cours',
      status_processing: 'En cours',
      status_shipped: 'Expédiée',
      status_delivered: 'Livrée',
      status_fulfilment_failed: 'Échec',
      status_refunded: 'Remboursée',
    },
    orderStatus: {
      title: 'Commande confirmée !',
      subtitle: 'Merci — vos pièces sont en préparation. Une confirmation a été envoyée à votre email.',
      trackOrderCta: 'Suivre la commande',
      notFoundTitle: 'Commande introuvable',
      notFoundBody: 'Nous n’avons pas trouvé cette commande sur cet appareil. Elle a peut-être été passée sur un autre navigateur ou supprimée du stockage.',
      stepOrdered: 'Commandée',
      stepInProgress: 'En cours',
      stepShipped: 'Expédiée',
      stepDelivered: 'Livrée',
      failedTitle: 'Échec de la préparation',
      failedSubtitle: 'La marque n’a pas pu finaliser cette commande — vous n’avez rien à faire. Le remboursement est en chemin vers votre moyen de paiement d’origine.',
      stage_fulfilment_failed: 'Échec de la préparation — cette commande n’a pas pu être finalisée. Un remboursement a été initié.',
      stage_refunded: 'Remboursée — le montant total a été retourné à votre moyen de paiement d’origine.',
      demoAdvance: 'Démo : avancer le statut',
      demoFail: 'Démo : simuler l’échec',
      demoRefund: 'Démo : émettre le remboursement',
      demoReset: 'Démo : réinitialiser la commande',
    },
    auth: {
      brand: 'Agbayemaara',
      welcomeBack: 'Bon retour',
      createAccount: 'Créer un compte',
      signInSubtitle: 'Connectez-vous pour accéder à vos commandes et à votre liste de souhaits.',
      signUpSubtitle: 'Rejoignez-nous et découvrez le meilleur de la mode africaine.',
      signIn: 'Se connecter',
      signUp: 'S’inscrire',
      fullName: 'Nom complet',
      fullNamePlaceholder: 'Votre nom complet',
      email: 'Email',
      emailPlaceholder: 'vous@example.com',
      password: 'Mot de passe',
      passwordPlaceholderSignin: '••••••••',
      passwordPlaceholderSignup: 'Min. 8 caractères',
      forgotPassword: 'Mot de passe oublié ?',
      signInButton: 'Se connecter',
      createAccountButton: 'Créer un compte',
      continueWithGoogle: 'Continuer avec Google',
      openCart: 'Ouvrir le panier',
      signInAction: 'Se connecter',
      toggleMenu: 'Basculer le menu',
    },
    discovery: {
      eyebrow: 'Le Feed',
      title: 'Découvrez la mode africaine, l\'histoire d\'abord',
      subtitle: 'Éditorial, lancements, étapes et les marques derrière — un seul fil, du plus récent au plus ancien.',
      forYou: 'POUR VOUS',
      followingTab: 'ABONNEMENTS',
      newBrands: 'NOUVELLES MARQUES',
      storyBadge: 'Histoire',
      stylingBadge: 'Styling',
      dropBadge: 'Lancement',
      milestoneBadge: 'Étape',
      newBrandBadge: 'Nouvelle marque',
      saleBadge: 'Soldes',
      shopTheLook: 'Acheter le look',
      readStory: 'Lire l’histoire',
      follow: 'Suivre',
      following: 'Suivi',
      viewBrand: 'Voir la marque',
      productsLabel: 'produits',
      firstDropTeaser: 'Premier lancement disponible',
      emptyFeed: 'Rien ici pour le moment — revenez bientôt.',
      emptyFollowingTitle: 'Votre fil vous attend',
      emptyFollowingBody: 'Suivez les marques que vous aimez et leurs histoires, lancements et étapes arriveront ici en premier.',
      emptyFollowingCta: 'Explorer Pour Vous',
      errorTitle: 'Le fil a rencontré un problème',
      errorBody: 'Une erreur est survenue lors du chargement de votre fil. Réessayez.',
      retry: 'Réessayer',
    },
    followingPage: {
      navLink: 'Abonnements',
      eyebrow: 'Vos abonnements',
      title: 'Abonnements',
      subtitle: 'Histoires, lancements, étapes et pièces des marques que vous suivez — un seul fil, du plus récent au plus ancien.',
      emptyTitle: 'Votre fil vous attend',
      emptyBody: 'Suivez les marques que vous aimez et leurs histoires, lancements, étapes et produits arriveront ici en premier. Commencez avec ces trois.',
      emptyCta: 'Explorer Découvrir',
      brandsFollowed: 'marques suivies',
    },
  },
}

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState('en')

  const getTranslationValue = (section, key) => {
    const parts = key.split('.')
    const fallbackLanguage = 'en'

    const resolve = (lang) => {
      let value = translations[lang]?.[section]
      for (const part of parts) {
        if (value && typeof value === 'object') {
          value = value[part]
        } else {
          return undefined
        }
      }
      return value
    }

    return resolve(language) ?? resolve(fallbackLanguage) ?? key
  }

  const value = useMemo(() => ({
    language,
    setLanguage,
    t: (section, key) => getTranslationValue(section, key),
    languages: [
      { code: 'en', label: 'English' },
      { code: 'es', label: 'Español' },
      { code: 'fr', label: 'Français' },
    ],
  }), [language])

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>
}

export const useLanguage = () => useContext(LanguageContext)
