import { createContext, useContext, useMemo, useState } from 'react'

const LanguageContext = createContext()

const translations = {
  en: {
    nav: {
      shop: 'Shop',
      home: 'Home',
      brands: 'Brands',
      signIn: 'Sign In / Register',
      language: 'Language',
    },
    landingNav: {
      home: 'Home',
      about: 'About',
      contact: 'Contact',
    },
    hero: {
      heading: 'Discover The Best African Talent',
      blurb: 'From their feed to your closet. Own the pieces your favorites are rocking. Shop the looks you love.',
      shopNow: 'Shop Now',
      downloadApp: 'Download App',
      featuredBrands: 'Featured Brands',
      viewAllBrands: 'View all brands',
      exploreBrand: 'Explore brand',
    },
    about: {
      heading: 'About Us',
      body1: 'Agbayemaara is a fashion e-commerce platform that celebrates African talent and culture. We are dedicated to showcasing the best of African fashion, connecting customers with unique and stylish pieces from across the continent. Our mission is to empower African designers and artisans while providing our customers with an exceptional shopping experience.',
      body2: 'At Agbayemaara, we believe in the power of fashion to tell stories and express individuality. We curate a diverse collection of clothing, accessories, and footwear that reflects the rich tapestry of African culture and creativity. Whether you are looking for traditional prints, contemporary designs, or statement pieces, you will find it all here.',
    },
    contact: {
      heading: 'Contact Us',
      intro: 'For inquiries, support, or feedback, please reach out to us at:',
      email: 'Email:',
      phone: 'Phone:',
      address: 'Address:',
      namePlaceholder: 'Your Name',
      emailPlaceholder: 'Your Email',
      messagePlaceholder: 'Your Message',
      send: 'Send Message',
    },
    footer: {
      rights: '© 2026 Agbayemaara. All rights reserved.',
      privacy: 'Privacy Policy',
      terms: 'Terms of Service',
      follow: 'Follow us on social media',
      join: 'Join our community',
    },
    shopHome: {
      title: 'All Products',
      searchPlaceholder: 'Search products...',
      searchAriaLabel: 'Search products',
      noProductsMessage: 'No products match the current filters yet.',
      categories: {
        all: 'All',
        clothes: 'Clothes',
        shoes: 'Shoes',
        bags: 'Bags',
        jewelries: 'Jewelries',
        hats: 'Hats',
      },
      genderFilters: {
        all: 'All',
        female: 'Female',
        male: 'Male',
      },
    },
    productCard: {
      addToCart: 'Add to Cart',
      added: 'Added',
    },
    productDetails: {
      back: 'Back to products',
      addToCart: 'Add to Cart',
      continueShopping: 'Continue Shopping',
      overview: 'Overview',
      fastDelivery: 'Fast delivery',
      fastDeliveryText: 'Estimated delivery shown at checkout.',
      qualityGuarantee: 'Quality guarantee',
      qualityGuaranteeText: 'Carefully selected fabric and finish.',
      care: 'Care instructions',
      notFound: 'Product not found',
      return: 'Return to shop',
    },
    brandsPage: {
      badge: 'Brand Directory',
      heading: 'Discover brands that define the collection.',
      blurb: 'Explore a curated grid of labels. Tap any brand to open a dedicated collection page with all of its products.',
      brands: 'Brands',
      styleRange: 'Style range',
      layout: 'Layout',
      featured: 'Featured labels',
      shopByBrand: 'Shop by brand',
      gridView: 'Grid View',
      collection: 'Collection',
      viewBrand: 'View brand',
      curated: 'Curated',
      grid: 'Grid',
    },
    brandDetails: {
      notFound: 'Brand not found',
      backToBrands: 'Back to brands',
      featuredBrand: 'Featured brand',
      products: 'products',
      curatedCollection: 'Curated collection',
      quickOverview: 'Quick overview',
      selectedProducts: 'Selected products',
      selectedProductsText: 'items currently available in this collection.',
      browseByBrand: 'Browse by brand',
      browseByBrandText: 'Every card below opens the product detail page for that item.',
      productsFound: 'products found',
      noProducts: 'No products are currently listed for this brand.',
      productsLabel: 'Products',
      collectionLabel: 'collection',
    },
    cart: {
      title: 'Your Cart',
      empty: 'Your cart is empty',
      continueShopping: 'Continue shopping',
      subtotal: 'Subtotal',
      shipping: 'Shipping and taxes calculated at checkout',
      checkout: 'Checkout',
      clearCart: 'Clear cart',
      brandFallback: 'Agbayemaara',
    },
    auth: {
      brand: 'Agbayemaara',
      welcomeBack: 'Welcome back',
      createAccount: 'Create account',
      signInSubtitle: 'Sign in to access your orders and wishlist.',
      signUpSubtitle: 'Join and discover the best of African fashion.',
      signIn: 'Sign In',
      signUp: 'Sign Up',
      fullName: 'Full Name',
      fullNamePlaceholder: 'Your full name',
      email: 'Email',
      emailPlaceholder: 'you@example.com',
      password: 'Password',
      passwordPlaceholderSignin: '••••••••',
      passwordPlaceholderSignup: 'Min. 8 characters',
      forgotPassword: 'Forgot password?',
      signInButton: 'Sign In',
      createAccountButton: 'Create Account',
      continueWithGoogle: 'Continue with Google',
      openCart: 'Open cart',
      signInAction: 'Sign in',
      toggleMenu: 'Toggle menu',
    },
  },
  es: {
    nav: {
      shop: 'Tienda',
      home: 'Inicio',
      brands: 'Marcas',
      signIn: 'Iniciar sesión / Registrarse',
      language: 'Idioma',
    },
    landingNav: {
      home: 'Inicio',
      about: 'Acerca de',
      contact: 'Contacto',
    },
    hero: {
      heading: 'Descubre el mejor talento africano',
      blurb: 'Desde su feed hasta tu armario. Haz tuyas las piezas que tus favoritos lucen. Compra los looks que te encantan.',
      shopNow: 'Comprar ahora',
      downloadApp: 'Descargar app',
      featuredBrands: 'Marcas destacadas',
      viewAllBrands: 'Ver todas las marcas',
      exploreBrand: 'Explorar marca',
    },
    about: {
      heading: 'Sobre nosotros',
      body1: 'Agbayemaara es una plataforma de moda en línea que celebra el talento y la cultura africanos. Nos dedicamos a mostrar lo mejor de la moda africana, conectando a los clientes con piezas únicas y elegantes de todo el continente. Nuestra misión es empoderar a diseñadores y artesanos africanos mientras ofrecemos a nuestros clientes una experiencia de compra excepcional.',
      body2: 'En Agbayemaara, creemos en el poder de la moda para contar historias y expresar la individualidad. Curamos una colección diversa de ropa, accesorios y calzado que refleja el rico tapiz de la cultura y la creatividad africanas. Ya sea que busques estampados tradicionales, diseños contemporáneos o piezas llamativas, aquí encontrarás todo.',
    },
    contact: {
      heading: 'Contáctanos',
      intro: 'Para consultas, soporte o comentarios, ponte en contacto con nosotros en:',
      email: 'Correo:',
      phone: 'Teléfono:',
      address: 'Dirección:',
      namePlaceholder: 'Tu nombre',
      emailPlaceholder: 'Tu correo',
      messagePlaceholder: 'Tu mensaje',
      send: 'Enviar mensaje',
    },
    footer: {
      rights: '© 2026 Agbayemaara. Todos los derechos reservados.',
      privacy: 'Política de privacidad',
      terms: 'Términos de servicio',
      follow: 'Síguenos en redes sociales',
      join: 'Únete a nuestra comunidad',
    },
    shopHome: {
      title: 'Todos los productos',
      searchPlaceholder: 'Buscar productos...',
      searchAriaLabel: 'Buscar productos',
      noProductsMessage: 'No hay productos que coincidan con los filtros actuales.',
      categories: {
        all: 'Todo',
        clothes: 'Ropa',
        shoes: 'Zapatos',
        bags: 'Bolsos',
        jewelries: 'Joyas',
        hats: 'Sombreros',
      },
      genderFilters: {
        all: 'Todo',
        female: 'Mujer',
        male: 'Hombre',
      },
    },
    productCard: {
      addToCart: 'Añadir al carrito',
      added: 'Añadido',
    },
    productDetails: {
      back: 'Volver a productos',
      addToCart: 'Añadir al carrito',
      continueShopping: 'Seguir comprando',
      overview: 'Resumen',
      fastDelivery: 'Entrega rápida',
      fastDeliveryText: 'La fecha estimada de entrega se muestra al finalizar la compra.',
      qualityGuarantee: 'Garantía de calidad',
      qualityGuaranteeText: 'Tela y acabado cuidadosamente seleccionados.',
      care: 'Instrucciones de cuidado',
      notFound: 'Producto no encontrado',
      return: 'Volver a la tienda',
    },
    brandsPage: {
      badge: 'Directorio de marcas',
      heading: 'Descubre las marcas que definen la colección.',
      blurb: 'Explora una cuadrícula curada de etiquetas. Toca cualquier marca para abrir una página dedicada con todos sus productos.',
      brands: 'Marcas',
      styleRange: 'Gama de estilo',
      layout: 'Diseño',
      featured: 'Etiquetas destacadas',
      shopByBrand: 'Comprar por marca',
      gridView: 'Vista en cuadrícula',
      collection: 'Colección',
      viewBrand: 'Ver marca',
      curated: 'Curada',
      grid: 'Cuadrícula',
    },
    brandDetails: {
      notFound: 'Marca no encontrada',
      backToBrands: 'Volver a marcas',
      featuredBrand: 'Marca destacada',
      products: 'productos',
      curatedCollection: 'Colección curada',
      quickOverview: 'Resumen rápido',
      selectedProducts: 'Productos seleccionados',
      selectedProductsText: 'artículos disponibles actualmente en esta colección.',
      browseByBrand: 'Explorar por marca',
      browseByBrandText: 'Cada tarjeta a continuación abre la página de detalles del producto para ese artículo.',
      productsFound: 'productos encontrados',
      noProducts: 'Actualmente no hay productos listados para esta marca.',
      productsLabel: 'Productos',
      collectionLabel: 'colección',
    },
    cart: {
      title: 'Tu carrito',
      empty: 'Tu carrito está vacío',
      continueShopping: 'Seguir comprando',
      subtotal: 'Subtotal',
      shipping: 'Envío e impuestos calculados al finalizar la compra',
      checkout: 'Pagar',
      clearCart: 'Vaciar carrito',
      brandFallback: 'Agbayemaara',
    },
    auth: {
      brand: 'Agbayemaara',
      welcomeBack: 'Bienvenido de nuevo',
      createAccount: 'Crear cuenta',
      signInSubtitle: 'Inicia sesión para ver tus pedidos y tu lista de deseos.',
      signUpSubtitle: 'Únete y descubre lo mejor de la moda africana.',
      signIn: 'Iniciar sesión',
      signUp: 'Registrarse',
      fullName: 'Nombre completo',
      fullNamePlaceholder: 'Tu nombre completo',
      email: 'Correo',
      emailPlaceholder: 'tu@correo.com',
      password: 'Contraseña',
      passwordPlaceholderSignin: '••••••••',
      passwordPlaceholderSignup: 'Mín. 8 caracteres',
      forgotPassword: '¿Olvidaste tu contraseña?',
      signInButton: 'Iniciar sesión',
      createAccountButton: 'Crear cuenta',
      continueWithGoogle: 'Continuar con Google',
      openCart: 'Abrir carrito',
      signInAction: 'Iniciar sesión',
      toggleMenu: 'Alternar menú',
    },
  },
  fr: {
    nav: {
      shop: 'Boutique',
      home: 'Accueil',
      brands: 'Marques',
      signIn: 'Se connecter / S’inscrire',
      language: 'Langue',
    },
    landingNav: {
      home: 'Accueil',
      about: 'À propos',
      contact: 'Contact',
    },
    hero: {
      heading: 'Découvrez le meilleur talent africain',
      blurb: 'De leur fil à votre dressing. Prenez les pièces que vos favoris portent. Achetez les looks que vous aimez.',
      shopNow: 'Acheter maintenant',
      downloadApp: 'Télécharger l’application',
      featuredBrands: 'Marques en vedette',
      viewAllBrands: 'Voir toutes les marques',
      exploreBrand: 'Explorer la marque',
    },
    about: {
      heading: 'À propos de nous',
      body1: 'Agbayemaara est une plateforme e-commerce de mode qui célèbre le talent et la culture africains. Nous nous consacrons à mettre en valeur le meilleur de la mode africaine, en connectant les clients à des pièces uniques et élégantes de tout le continent. Notre mission est de donner de la voix aux créateurs et artisans africains tout en offrant à nos clients une expérience d’achat exceptionnelle.',
      body2: 'Chez Agbayemaara, nous croyons au pouvoir de la mode pour raconter des histoires et exprimer l’individualité. Nous sélectionnons une collection variée de vêtements, accessoires et chaussures qui reflète la richesse de la culture et de la créativité africaines. Que vous recherchiez des imprimés traditionnels, des designs contemporains ou des pièces marquantes, vous trouverez tout ici.',
    },
    contact: {
      heading: 'Contactez-nous',
      intro: 'Pour toute demande, assistance ou retour, n’hésitez pas à nous contacter à :',
      email: 'Email :',
      phone: 'Téléphone :',
      address: 'Adresse :',
      namePlaceholder: 'Votre nom',
      emailPlaceholder: 'Votre email',
      messagePlaceholder: 'Votre message',
      send: 'Envoyer le message',
    },
    footer: {
      rights: '© 2026 Agbayemaara. Tous droits réservés.',
      privacy: 'Politique de confidentialité',
      terms: 'Conditions d’utilisation',
      follow: 'Suivez-nous sur les réseaux sociaux',
      join: 'Rejoignez notre communauté',
    },
    shopHome: {
      title: 'Tous les produits',
      searchPlaceholder: 'Rechercher des produits...',
      searchAriaLabel: 'Rechercher des produits',
      noProductsMessage: 'Aucun produit ne correspond aux filtres actuels.',
      categories: {
        all: 'Tous',
        clothes: 'Vêtements',
        shoes: 'Chaussures',
        bags: 'Sacs',
        jewelries: 'Bijoux',
        hats: 'Chapeaux',
      },
      genderFilters: {
        all: 'Tous',
        female: 'Femme',
        male: 'Homme',
      },
    },
    productCard: {
      addToCart: 'Ajouter au panier',
      added: 'Ajouté',
    },
    productDetails: {
      back: 'Retour aux produits',
      addToCart: 'Ajouter au panier',
      continueShopping: 'Continuer les achats',
      overview: 'Aperçu',
      fastDelivery: 'Livraison rapide',
      fastDeliveryText: 'La livraison estimée est indiquée au moment du paiement.',
      qualityGuarantee: 'Garantie de qualité',
      qualityGuaranteeText: 'Tissu et finition soigneusement sélectionnés.',
      care: 'Instructions d’entretien',
      notFound: 'Produit introuvable',
      return: 'Retourner à la boutique',
    },
    brandsPage: {
      badge: 'Annuaire des marques',
      heading: 'Découvrez les marques qui définissent la collection.',
      blurb: 'Explorez une grille soignée de labels. Touchez une marque pour ouvrir une page dédiée avec tous ses produits.',
      brands: 'Marques',
      styleRange: 'Gammes de style',
      layout: 'Mise en page',
      featured: 'Labels en vedette',
      shopByBrand: 'Acheter par marque',
      gridView: 'Vue grille',
      collection: 'Collection',
      viewBrand: 'Voir la marque',
      curated: 'Sélectionnée',
      grid: 'Grille',
    },
    brandDetails: {
      notFound: 'Marque introuvable',
      backToBrands: 'Retour aux marques',
      featuredBrand: 'Marque en vedette',
      products: 'produits',
      curatedCollection: 'Collection sélectionnée',
      quickOverview: 'Aperçu rapide',
      selectedProducts: 'Produits sélectionnés',
      selectedProductsText: 'articles actuellement disponibles dans cette collection.',
      browseByBrand: 'Parcourir par marque',
      browseByBrandText: 'Chaque carte ci-dessous ouvre la page de détail du produit correspondant.',
      productsFound: 'produits trouvés',
      noProducts: 'Aucun produit n’est actuellement listé pour cette marque.',
      productsLabel: 'Produits',
      collectionLabel: 'collection',
    },
    cart: {
      title: 'Votre panier',
      empty: 'Votre panier est vide',
      continueShopping: 'Continuer les achats',
      subtotal: 'Sous-total',
      shipping: 'Frais de livraison et taxes calculés au paiement',
      checkout: 'Commander',
      clearCart: 'Vider le panier',
      brandFallback: 'Agbayemaara',
    },
    auth: {
      brand: 'Agbayemaara',
      welcomeBack: 'Bon retour',
      createAccount: 'Créer un compte',
      signInSubtitle: 'Connectez-vous pour accéder à vos commandes et à votre liste de souhaits.',
      signUpSubtitle: 'Rejoignez-nous et découvrez le meilleur de la mode africaine.',
      signIn: 'Se connecter',
      signUp: 'S’inscrire',
      fullName: 'Nom complet',
      fullNamePlaceholder: 'Votre nom complet',
      email: 'Email',
      emailPlaceholder: 'vous@example.com',
      password: 'Mot de passe',
      passwordPlaceholderSignin: '••••••••',
      passwordPlaceholderSignup: 'Min. 8 caractères',
      forgotPassword: 'Mot de passe oublié ?',
      signInButton: 'Se connecter',
      createAccountButton: 'Créer un compte',
      continueWithGoogle: 'Continuer avec Google',
      openCart: 'Ouvrir le panier',
      signInAction: 'Se connecter',
      toggleMenu: 'Basculer le menu',
    },
  },
}

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState('en')

  const value = useMemo(() => ({
    language,
    setLanguage,
    t: (section, key) => translations[language]?.[section]?.[key] ?? translations.en?.[section]?.[key] ?? key,
    languages: [
      { code: 'en', label: 'English' },
      { code: 'es', label: 'Español' },
      { code: 'fr', label: 'Français' },
    ],
  }), [language])

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>
}

export const useLanguage = () => useContext(LanguageContext)
